- hosts: localhost
  vars:
    settings:
      HELLO: nurse
      URL: https://appfromansible.herokuapp.com/
  vars_files:
    - vars/credentials.yml
  tasks:
    - name: Get facts
      heroku: 
        apikey: "{ {heroku_api_key} }"
        app: "{ {items} }"
      with_items:
        - "{ {heroku_existing_application_name} }"
      ignore_errors: yes
    - name : Create App
      heroku:
        apikey: "{ {heroku_api_key} }"
        app: "{ {heroku_app_name} }"
        command: "create"